app/models/auth.py
from app.extensions import db, UserMixin

class Admin(db.Model, UserMixin):
    
    __tablename__ = 'admins'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(30), unique=False, nullable=False)

app/models/post.py
from app.extensions import db

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150))
    content = db.Column(db.Text)
    date_created = db.Column(db.Text)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    

    def __repr__(self):
        return f'<Post "{self.title}">'

class Category(db.Model):
    
    id = db.Column(db.Integer, primary_key=True)
    category_name = db.Column(db.String(30))
    
    def __repr__(self):
        return f'<Category "{self.category_name}">'

app/__init__.py
from flask import Flask

from config import Config
from app.extensions import db, LoginManager, login_required, setup_logging
import os

from app.models.auth import Admin

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Initialize Flask extensions here
    db.init_app(app)
    
    setup_logging(app)
    
    login_manager = LoginManager()
    login_manager.init_app(app)
    
    @login_manager.user_loader
    def load_user(user_id):
        
        return Admin.query.get(int(user_id))
    
   
    # Register blueprints here
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)
    
    # Register post blueprint and add a prefix so /posts/ /posts/categories
    from app.posts import bp as posts_bp
    app.register_blueprint(posts_bp, url_prefix='/posts')
    
    # Register auth blueprint
    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    @app.route('/test/')
    def test_page():
        return '<h1>Testing the Flask Application Factory Pattern</h1>'

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
# The init.py file make this importing of bp possible.
from app.main import bp
from flask import render_template
from flask_login import current_user


@bp.route('/')
def index():
    
    is_authenticated =  current_user.is_authenticated
    return render_template('index.html', is_authenticated=is_authenticated)

app/posts/__init__.py
from flask import Blueprint, url_for

bp = Blueprint('posts', __name__)


from app.posts import routes

app/posts/routes.py
from flask import render_template, request, send_from_directory, url_for, redirect, flash
from app.posts import bp
from app.extensions import db, login_required
from werkzeug.utils import secure_filename
import base64
from bs4 import BeautifulSoup
import os
from datetime import datetime
from icecream import ic

IMAGE_FOLDER = 'app/static/uploads'

from app.models.post import Post, Category
def getCategories():
    
    categories = Category.query.all()
    
    return categories


@bp.route('/', methods=['GET', 'POST'])
@login_required
def index():
    
    categories = getCategories()
    

    if request.method == 'POST':
        
        title = request.form.get('title')
        editor_data = request.form.get('editordata')
        category = request.form.get('category_select')
        
        
        converted_html = convert_base64_to_image(editor_data)
        
        current_date = datetime.now()

        formatted_date = current_date.strftime("%B %d %Y")
        
    
        insert_content = Post(title=title, content=converted_html, date_created=formatted_date, category_id=category)
        
        db.session.add(insert_content)
        db.session.commit()
        
        flash("Succesfully registered content")
    
    return render_template('posts/index.html', category_names=categories)

@bp.route('/categories/')
def categories():
    return render_template('posts/categories.html')


# -------------------- IMAGE HANDLING SECTION BELOW --------------------
@bp.route("/uploads/<filename>")
def uploaded_file(filename):
    return send_from_directory(IMAGE_FOLDER, filename)



def convert_base64_to_image(html_content):
    # Utilize BS4 as they can easily get all images on an HTML content
    soup = BeautifulSoup(html_content, 'html.parser')
    
    
    for img in soup.find_all('img'):
        
        
        if img.get('src') and img.get('src').startswith('data:image'):
            base64_data = img['src']
            
            filename = secure_filename(f"image_{len(os.listdir(IMAGE_FOLDER)) + 1}.png")
            save_base64_image(base64_data, filename)
            
            img['src'] = url_for('posts.uploaded_file', filename=filename)
            
    return str(soup)



def save_base64_image(base64_data, filename):
    img_data_decoded = base64.b64decode(base64_data.split(",")[1])
    with open(os.path.join(IMAGE_FOLDER, filename), 'wb') as f:
        f.write(img_data_decoded)
        
        
# -------------------- IMAGE HANDLING SECTION ABOVE --------------------

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Alexander Macenas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">

</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand ms-2" href="#" style="font-weight:900;">MEDIO.</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end me-3" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="#">About Me</a>
                    <a class="nav-link" href="#">About Medio</a>
                    <a class="nav-link" href="#">Pricing</a>
                </div>
            </div>
        </div>
    </nav>
    <div class="content">
        {% block content %} {% endblock %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="row d-flex">
    <div class="col-lg-8" style="overflow-y: auto;">
        <div class="container-fluid" style="width:70%; margin-left:25%; margin-top:40px;">
            <ul class="nav nav-tabs border border-top-0 border-bottom-0 border-start-0" id="myTab" role="tablist">

                {% if is_authenticated %}
                <li class="nav-item" role="presentation">
                    <button class="nav-link border-0 border-start-0" id="" data-bs-toggle="tab"
                        data-bs-target="" type="button" role="" aria-controls=""
                        aria-selected="false">+</button>
                </li>
                {% endif %}

                <li class="nav-item" role="presentation">
                    <button class="nav-link border-0 border-start-0 active" id="home-tab" data-bs-toggle="tab"
                        data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane"
                        aria-selected="true">Home</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link border-0 border-start-0" id="profile-tab" data-bs-toggle="tab"
                        data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane"
                        aria-selected="false">Profile</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link border-0 border-start-0" id="contact-tab" data-bs-toggle="tab"
                        data-bs-target="#contact-tab-pane" type="button" role="tab" aria-controls="contact-tab-pane"
                        aria-selected="false">Contact</button>
                </li>
            </ul>
            
            <div class="tab-content my-5 " id="myTabContent">
                <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab"
                    tabindex="0">

                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-9">
                                    <h4 class="card-title" style="font-weight: 700;">Some Title</h4>
                                    <p class="card-text">A very nice description
                                        about it you dish? bro?
                                        A very nice description about it you dish? bro
                                        A very nice description about it you dish? bro?
                                        A very nice description about it you dish? bro
                                        A very nice description about it you dish? bro?
                                        Perform text-truncate on Py
                                    </p>
                                    <div style="display: flex;">
                                        <div class="pills">Cybersecurity</div>
                                        <div class="mt-2" style="margin-left: 10px; color: gray;">7 min read</div>
                                    </div>

                                </div>
                                <div class="col-sm-3">
                                    <img src="https://plus.unsplash.com/premium_photo-1711508491465-1f242f42c826?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                                        class="img-fluid" alt="sans"
                                        style="max-width: 100%; height: auto; max-height: 180px; object-fit: cover;">
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>

                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-9">
                                    <h4 class="card-title" style="font-weight: 700;">Some Title</h4>
                                    <p class="card-text">A very nice description
                                        about it you dish? bro?
                                        A very nice description about it you dish? bro
                                        A very nice description about it you dish? bro?
                                        A very nice description about it you dish? bro
                                        A very nice description about it you dish? bro?
                                        Perform text-truncate on Py
                                    </p>
                                    <div style="display: flex;">
                                        <div class="pills">Cybersecurity</div>
                                        <div class="mt-2" style="margin-left: 10px; color: gray;">7 min read</div>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <img src="https://plus.unsplash.com/premium_photo-1711508491465-1f242f42c826?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                                        class="img-fluid" alt="sans"
                                        style="max-width: 100%; height: auto; max-height: 180px; object-fit: cover;">


                                </div>
                            </div>
                        </div>
                    </div>

                    <br>
                </div>

                <!-- Profile Section Tab -->
                <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab"
                tabindex="0">

                <h1>Alexander Macenas</h1>
                <br>
                <h5>Aspiring Cybersecurity Professional</h5>
                <br>
                <p>Aspiring Cybersecurity professional - actively searching for a security role. Always eager to learn other technical areas of cybersecurity!</p>
               
                <h2>Trainings & Certifications</h2>
                <ul>
                    <li><strong>Google Cybersecurity Professional Certificate</strong>: Includes Linux, SQL and Python labs</li>
                    <li><strong>TCM Security's Practical Ethical Hacking:</strong> Setup and attack Active Directory laboratory</li>
                    <li><strong>TCM Security's Malware Analysis Triage:</strong> Setup and perform analysis on real world samples</li>
                </ul>

                <br>
                <h2>Practical Projects</h2>
                    <ul>
                        <li>
                            Expanded the Active Directory lab and added Wazuh as a SIEM to detect and log attacks.
                        </li>
                        <li>
                            Setup and configure Opnsense Firewall
                        </li>
                        <li>
                            Built a Personal Website using Python Flask
                        </li>
                    </ul>

                    <br>
                    <h2>Experiences</h2>
                    <h5>Orkestra Communications, QC - 2024</h5>
                    <h5>Help Desk</h5>
                    <p>Duties Include:</p>
                    <ul>
                        <li>
                            Performed data entry of assets including computers, IP address, mouse, keyboards and their respective agents assigned, ensuring comprehensive asset tracking
                        </li>
                        <li>Developed and implemented a web application to enhance accuracy and efficiency in inventory management</li>
                        <li>
                            Basic IT Troubleshooting of hardware and network issues
                        </li>
                        <li>
                            Setup and configured Windows agent PCs, ensuring they met security standards and were properly integrated into the network through Fortigate Firewall
                        </li>
                    </ul>

                    <h3>Skills</h3>
                    <p>Python, Malware Analysis, Active Directory, Opnsense, SQL, Wazuh, Linux</p>

                </div>

                <div class="tab-pane fade" id="contact-tab-pane" role="tabpanel" aria-labelledby="contact-tab"
                tabindex="0">

                <h5>Email Address</h5>
                <div class="clipboard-example align-items-center w-50">
                    <div class="input-group mb-3">
                        <input id="in01"
                               type="text"
                               class="form-control"
                               placeholder="Email Address"
                               aria-label="BTC Address"
                               aria-describedby="btn01"
                               value="alexxmacenas@gmail.com"
                               readonly>
                        <button id="btn01"
                                class="btn btn-secondary"
                                type="button"
                                data-clipboard-demo=""
                                data-clipboard-target="#in01"
                                data-bs-toggle="tooltip"
                                data-bs-placement="bottom"
                                title="Copy to Clipboard"
                        >Copy</button>
                    </div>
                </div>

                <h5><a>LinkedIn</a></h5>
               <h5><a>Github - Projects</a></h5>
                </div>

            </div>
        </div>
    </div>

    <!-- Removed on medium size screens -->
    <div class="col-lg-4 d-none d-lg-block">
        <div class="container-fluid" style="margin: 40px 20px;">
            <p style="font-weight: 700;">Recently Published</p>
            <div class="div">


                <div class="row">
                    <div class="col-lg-12">
                        <p class="text-truncate mb-2" style="color: gray;">L 20 min read - December 22 2024</p>
                        <h5 class="fw-bold" style="width:65%; margin-bottom: 5px;">THIS IS A H3 ELEMENT AND MUCH LONGER
                            AND LARGER</h5>
                    </div>
                </div>
                <p clas="mt-1"></p>

                <div class="row">
                    <div class="col-lg-12">
                        <p class="text-truncate mb-2" style="color: gray;">L 20 min read - December 22 2024</p>
                        <h5 class="fw-bold" style="width:65%; margin-bottom: 5px;">THIS IS A H3 ELEMENT AND MUCH LONGER
                            AND LARGER</h5>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <p class="text-truncate mb-2" style="color: gray;">L 20 min read - December 22 2024</p>
                        <h5 class="fw-bold" style="width:65%; margin-bottom: 5px;">THIS IS A H3 ELEMENT AND MUCH LONGER
                            AND LARGER</h5>
                    </div>
                </div>

            </div>

            <div>
                <p class="task-item mt-4" style="font-weight: 700;">What I am doing now</p>
                <p class="task-item">1. Personal Website Development - <span id="timer1">00:00:00</span></p>
                <p class="task-item">2. Second Time To Track (Paused) - <span id="timer2">00:00:00</span></p>
            </div>


            <div id="task-list" style="max-width: 60%;">
                <div class="row">

                    <p class="mt-4" style="font-weight: 700;">Topics</p>

                </div>
                <!-- Topics down here ignore above -->
                <div id="topics-row" class="row"></div>
            </div>

            <!-- Recently followed people -->
            <div>
                <p class="task-item mt-4" style="font-weight: 700;">I recently followed them</p>
                <p class="task-item">AMazing MAN</p>
                <p class="task-item">GEMINI</p>
            </div>


        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='js/pills.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/clipboard@2.0.6/dist/clipboard.min.js"></script>

<script>
    document.querySelectorAll('.nav-link').forEach(tab => {
        tab.addEventListener('click', () => {
            // Remove active class from all tabs
            document.querySelectorAll('.nav-link').forEach(tab => {
                tab.classList.remove('active');
                tab.classList.remove('active-tab-border');
            });

            // Add active class to the clicked tab
            tab.classList.add('active');
            tab.classList.add('active-tab-border');
        });
    });

</script>

<script>
    let btn = document.getElementById('btn01');
    let clipboard = new ClipboardJS(btn);

    clipboard.on('success', function(e) {
        console.log(e);
    });

    clipboard.on('error', function(e) {
        console.log(e);
    });
</script>
    

{% endblock %}

app/templates/posts/categories.html
{% extends 'base.html' %}

{% block content %}
<span class="title">
    <h1>{% block title %} Categories {% endblock %}</h1>
</span>
<div class="content">
    <h2>This is the categories page within the posts blueprint</h2>

</div>
{% endblock %}

app/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    <h1 class="text-center">Create a Blog</h1>
    <form method="POST" action="{{ url_for('posts.index') }}">
        <label for="title" class="form-label">Title</label>
        <input type="text" class="form-control" id="title" name="title">
        <br>
        <textarea id="summernote" name="editordata"></textarea>

        <select name="category_select" class="form-select" aria-label="Default select example"
            style="margin-top:20px; margin-bottom: 20px;">
            <option selected disabled>Choose a category</option>
            {% for category_name in category_names %}
            <option value="{{ category_name.id }}">{{ category_name.category_name }}</option>
            {% endfor %}
        </select>


        <div class="button-container pb-5">
            <button type="submit" class="btn btn-outline-success">Create</button>
            <button type="button" class="btn btn-outline-warning"
                onclick="window.location.href='/users/akex'">Discard</button>
        </div>
    </form>
</div>


<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script>
    $(document).ready(function () {
        $('#summernote').summernote({
            codeviewFilter: true,
            codeviewIframeFilter: true,
            height: 400,
            placeholder: "Type something here"
        });
    });



</script>
{% endblock %}